using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SpecterSDK.APIModels.ClientModels;
using SpecterSDK.APIModels.ClientModels.v1;
using SpecterSDK.Shared.Networking.Models;

namespace SpecterSDK.API.v1.Matches
{
    /// <summary>
    /// Represents the request to end a match session.
    /// This request should hold information about the participants, and their respective
    /// outcomes for the match according to the <see cref="SPEndMatchSessionUserInfo"/> specs.
    /// </summary>
    [Serializable]
    public class SPEndMatchSessionRequest : SPApiRequestBase
    {
        /// <summary>
        /// The ID of the match session generated by either the start or create match session calls.
        /// </summary>
        public string matchSessionId;
        
        /// <summary>
        /// Information about the participants of the match.
        /// </summary>
        public List<SPEndMatchSessionUserInfo> userInfo;
    }

    /// <summary>
    /// Represents the result of ending a match session.
    /// </summary>
    public class SPEndMatchSessionResult : SpecterApiResultBase<SPMatchSessionResponseData>
    {
        // The match session ID as sent in the request.
        public string MatchSessionId;

        protected override void InitSpecterObjectsInternal()
        {
            MatchSessionId = Response.data.matchSessionId;
        }
    }

    public partial class SPMatchesApiClient
    {
        /// <summary>
        /// Asynchronously ends a match session and returns the result.
        /// </summary>
        /// <param name="request"><see cref="SPEndMatchSessionRequest"/> containing details about the match session to be ended.</param>
        /// <returns>A Task representing the asynchronous operation, with <see cref="SPEndMatchSessionResult"/> as the result type.</returns>
        public async Task<SPEndMatchSessionResult> EndMatchSessionAsync(SPEndMatchSessionRequest request)
        {
            var result = await PostAsync<SPEndMatchSessionResult, SPMatchSessionResponseData>("/v1/client/matches/end-session", AuthType, request);
            return result;
        }

    }
}
